icons = "awesome"

[theme]
name = "slick"
#[theme.overrides]
#idle_bg = "#123456"
#idle_fg = "#abcdef"

[[block]]
block = "custom"
interval = 5
command = "pgrep -x openvpn &> /dev/null && echo \"VPN ON\""

[[block]]
block = "disk_space"
path = "/"
alias = "/"
info_type = "available"
unit = "GB"
interval = 20

[[block]]
block = "disk_space"
path = "/home"
alias = "/home"
info_type = "available"
unit = "GB"
interval = 20

[[block]]
block = "disk_space"
path = "/mnt/ssd"
alias = "/mnt/ssd"
info_type = "available"
unit = "GB"
interval = 20

[[block]]
block = "memory"
display_type = "memory"
format_mem = "{Mup}%"
format_swap = "{SUp}%"

[[block]]
block = "cpu"
format = "{barchart}"
interval = 1

[[block]]
block = "load"
interval = 1
format = "{1m}"

[[block]]
block = "sound"

[[block]]
block = "net"
device = "enp9s0"
ip = false
interval = 5
use_bits = false

[[block]]
block = "temperature"
collapsed = false
interval = 5
format = "{average}°"
chip = "k10temp-pci-00c3"

[[block]]
block = "time"
interval = 60
format = "%a %d/%m %R"
