[[profile]]
name = "desktop"
exec = [
        "notify-send shikane \"Profile $SHIKANE_PROFILE_NAME has been applied\"",
        "swaymsg workspace 1, move workspace to DP-10",
        "swaymsg workspace 2, move workspace to DP-9",
        "swaymsg workspace 3, move workspace to DP-10",
        "swaymsg workspace 4, move workspace to DP-10",
        "swaymsg workspace 5, move workspace to DP-10",
]

[[profile.output]]
search = ["m=E231W", "s=54338794NB   ", "v=NEC Corporation"]
enable = true
mode = "best"
position = "0,0"
[[profile.output]]
search = ["m=E231W", "s=4X334225NB   ", "v=NEC Corporation"]
enable = true
mode = "best"
position = "1920,0"
[[profile.output]]
search = "n=eDP-1"
enable = false

[[profile]]
name = "notebook"
exec = [
        "notify-send shikane \"Profile $SHIKANE_PROFILE_NAME has been applied\"",
        "swaymsg workspace 1, move workspace to eDP-1",
        "swaymsg workspace 2, move workspace to eDP-1",
        "swaymsg workspace 3, move workspace to eDP-1",
        "swaymsg workspace 4, move workspace to eDP-1",
        "swaymsg workspace 5, move workspace to eDP-1",
]

[[profile.output]]
search = "eDP-1"
enable = true
