[[profile]]
name = "desktop"
exec = [
        "notify-send shikane \"Profile $SHIKANE_PROFILE_NAME has been applied\"",
        "swaymsg workspace 1, move workspace to DP-8",
        "swaymsg workspace 2, move workspace to DP-8",
        "swaymsg workspace 3, move workspace to DP-8",
        "swaymsg workspace 4, move workspace to DP-8",
        "swaymsg workspace 5, move workspace to DP-8",
        "nmcli c d "
]

[[profile.output]]
search = "H27P6"
enable = true
mode = "best"
position = "0,0"
scale = 1.3
adaptive_sync = true

[[profile.output]]
search = "n=eDP-1"
enable = true
mode = "best"
position = "3040,0"
adaptive_sync = true

[[profile]]
name = "notebook"
exec = [
        "notify-send shikane \"Profile $SHIKANE_PROFILE_NAME has been applied\"",
        "swaymsg workspace 1, move workspace to eDP-1",
        "swaymsg workspace 2, move workspace to eDP-1",
        "swaymsg workspace 3, move workspace to eDP-1",
        "swaymsg workspace 4, move workspace to eDP-1",
        "swaymsg workspace 5, move workspace to eDP-1",
]

[[profile.output]]
search = "eDP-1"
enable = true
