format = """
$username\
$hostname\
$shlvl\
$directory\
$git_branch\
$git_commit\
$git_state\
$git_status\
$python\
$package\
$dart\
$dotnet\
$rust\
$nix_shell\
$memory_usage\
$env_var\
$custom\
$line_break\
$jobs\
$battery\
$time\
$status\
$character"""

# Don't print a new line at the start of the prompt
add_newline = false
command_timeout = 100

[line_break]
disabled = true

[character]
vicmd_symbol = "[V](bold green) "

[hostname]
ssh_only = false
format = "on [$hostname](bold red) "
trim_at = ".redhat.com"
disabled = false

[directory]
truncation_length = 4
truncate_to_repo = false
truncation_symbol = "…/"
