export PATH=$HOME/bin:/usr/local/bin:$HOME/.local/bin:$HOME/.npm-packages/bin:$HOME/.cargo/bin:$PATH:$HOME/.yarn/bin:$HOME/.config/yarn/global/node_modules/.bin:$PATH
# export MANPATH="/usr/local/man:$MANPATH"

# Rebuilds the cache of executable commands
zstyle ":completion:*:commands" rehash 1


# Keep 99999 lines of history within the shell and save it to ~/.zsh_history:
HISTSIZE=99999
SAVEHIST=99999
HISTFILE=~/.zsh_history

# rustup
fpath+=~/.zfunc

# Use modern completion system
autoload -Uz compinit
compinit

zstyle ':completion:*' auto-description 'specify: %d'
zstyle ':completion:*' completer _expand _complete _correct _approximate
zstyle ':completion:*' format 'Completing %d'
zstyle ':completion:*' group-name ''
zstyle ':completion:*' menu select=2 eval "$(dircolors -b)"
zstyle ':completion:*:default' list-colors ${(s.:.)LS_COLORS}
zstyle ':completion:*' list-colors ''
zstyle ':completion:*' list-prompt %SAt %p: Hit TAB for more, or the character to insert%s
zstyle ':completion:*' matcher-list '' 'm:{a-z}={A-Z}' 'm:{a-zA-Z}={A-Za-z}' 'r:|[._-]=* r:|=* l:|=*'
zstyle ':completion:*' menu select=long
zstyle ':completion:*' select-prompt %SScrolling active: current selection at %p%s
zstyle ':completion:*' use-compctl false
zstyle ':completion:*' verbose true

zstyle ':completion:*:*:kill:*:processes' list-colors '=(#b) #([0-9]#)*=0=01;31'
zstyle ':completion:*:kill:*' command 'ps -u $USER -o pid,%cpu,tty,cputime,cmd'

untar (){
    for i in *.$1; do tar xvf $i; done
}

uzip (){
    for i in *.zip; do unzip $i; done
}

ungzip (){
    for i in *.gz; do gunzip $i; done
}

findfunlib (){
    scanelf -l -s $1 | grep $1
}

alias tmux='tmux -2'
alias vim='nvim'
alias vi='nvim'
alias muttya='mutt -F ~/.muttrc.yahoo'
alias mutt='neomutt'
alias ssh='ssh -X'
alias rtv='RTV_BROWSER=google-chrome rtv'
alias sudo='sudo '
alias apg="apg -a 0 -M SNcl -n 8 -x 12 -m 10"

# Get the bash behaviour when trying to complete files
setopt nonomatch

fpath+=${ZDOTDIR:-~}/.zsh_functions

# fzf 
[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh
export FZF_DEFAULT_COMMAND='fd --type f'
export FZF_DEFAULT_OPTS="--layout=reverse --inline-info"
export FZF_CTRL_T_COMMAND="$FZF_DEFAULT_COMMAND"

# Workaround for bomgar fonts
export _JAVA_OPTIONS='-Dawt.useSystemAAFontSettings=gasp'

# Starship
eval "$(starship init zsh)"
source <(sheldon source)

