# Only to test perf
# zmodload zsh/zprof
export PATH=$HOME/bin:/usr/local/bin:$HOME/.local/bin:$HOME/.npm-packages/bin:$HOME/.cargo/bin:$PATH:$HOME/.yarn/bin:$HOME/.config/yarn/global/node_modules/.bin:$PATH
# export MANPATH="/usr/local/man:$MANPATH"

# Rebuilds the cache of executable commands
zstyle ":completion:*:commands" rehash 1

# Set some useful options
setopt COMPLETE_IN_WORD    # Complete from both ends of a word.
setopt ALWAYS_TO_END       # Move cursor to the end of a completed word.
setopt PATH_DIRS           # Perform path search even on command names with slashes.
setopt AUTO_MENU           # Show completion menu on a successive tab press.
setopt AUTO_LIST           # Automatically list choices on ambiguous completion.
setopt AUTO_PARAM_SLASH    # If completed parameter is a directory, add a trailing slash.
setopt EXTENDED_GLOB       # Needed for file modification glob modifiers with compinit
setopt MENU_COMPLETE     # Do not autoselect the first completion entry.

# Keep 99999 lines of history within the shell and save it to ~/.zsh_history:
HISTSIZE=99999
SAVEHIST=99999
HISTFILE=~/.zsh_history

# custom functions
fpath+=~/.zfunc
if [[ -d ~/.zfunc ]]; then
    for file in $(ls ~/.zfunc);
    do
        autoload $file
    done
fi

# Use modern completion system
autoload -Uz compinit
compinit

# Use cache
zstyle ':completion:*' use-cache on
zstyle ':completion:*' cache-path ~/.zsh/cache
# Disable user completion for ssh
zstyle ':completion:*:ssh:argument-1:*' tag-order hosts
zstyle ':completion:*' completer _expand _complete _ignored _correct _approximate
zstyle ':completion:*' expand prefix suffix
zstyle ':completion:*' file-sort name
zstyle ':completion:*' list-colors ''
zstyle ':completion:*' list-prompt %SAt %p: Hit TAB for more, or the character to insert%s
zstyle ':completion:*' list-suffixes true
zstyle ':completion:*' max-errors 2
zstyle ':completion:*' menu select=1
zstyle ':completion:*' select-prompt %SScrolling active: current selection at %p%s
zstyle ':completion:*' special-dirs true
zstyle ':completion:*' squeeze-slashes true
zstyle ':completion:*' verbose true
zstyle ':completion:*' use-compctl false
zstyle ':completion:*:*:kill:*:processes' list-colors '=(#b) #([0-9]#)*=0=01;31'
zstyle ':completion:*:kill:*' command 'ps -u $USER -o pid,%cpu,tty,cputime,cmd'
# Directories
zstyle ':completion:*:default' list-colors ${(s.:.)LS_COLORS}
zstyle ':completion:*:*:cd:*' tag-order local-directories directory-stack path-directories
zstyle ':completion:*:*:cd:*:directory-stack' menu yes select
zstyle ':completion:*:-tilde-:*' group-order 'named-directories' 'path-directories' 'users' 'expand'
zstyle ':completion:*' squeeze-slashes true
zstyle :compinstall filename '/home/plambri/.zshrc'

# load bash autocompletion
autoload bashcompinit
bashcompinit


untar (){
    for i in *.$1; do tar xvf $i; done
}

uzip (){
    for i in *.zip; do unzip $i; done
}

ungzip (){
    for i in *.gz; do gunzip $i; done
}

findfunlib (){
    scanelf -l -s $1 | grep $1
}

alias tmux='tmux -2'
alias vim='nvim'
alias vi='nvim'
alias muttya='mutt -F ~/.muttrc.yahoo'
alias mutt='neomutt'
alias ssh='ssh -X'
alias rtv='RTV_BROWSER=google-chrome rtv'
alias sudo='sudo '
alias apg="apg -a 0 -M SNcl -n 8 -x 12 -m 10"

# Get the bash behaviour when trying to complete files
setopt nonomatch

fpath+=${ZDOTDIR:-~}/.zsh_functions

# fzf 
[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh
export FZF_DEFAULT_COMMAND='fd --type f'
export FZF_DEFAULT_OPTS="--layout=reverse --inline-info"
export FZF_CTRL_T_COMMAND="$FZF_DEFAULT_COMMAND"

# Workaround for bomgar fonts
export _JAVA_OPTIONS='-Dawt.useSystemAAFontSettings=gasp'

# Sane history backward search
bindkey '\e[A' history-beginning-search-backward
bindkey '\e[B' history-beginning-search-forward

# Move back/forward one word
bindkey "^[[1;5C" forward-word
bindkey "^[[1;5D" backward-word

# Begin/end keys
bindkey "\033[1~" beginning-of-line
bindkey "^[[H" beginning-of-line
bindkey "\033[4~" end-of-line
bindkey "^[[4~" end-of-line

# Delete key
bindkey    "^[[3~"          delete-char
bindkey    "^[3;5~"         delete-char
bindkey    "^[[P"         delete-char

# urlscan browser
export BROWSER=qutebrowser

# Starship
eval "$(starship init zsh)"
source <(sheldon source)
# Only to test perf
# zprof
